### ISSUE TITLE
Проверки так не работают

### ISSUE THREAD

**Issue by SuperLalka** [igorKichkar/Parking-lot-management#4]
https://github.com/igorKichkar/Parking-lot-management/blob/a57352c5805bcae40555b02cf1ba0e58ef231314/parking/views.py#L55

Проверка с оператором and в любом случае проверяют и левую и правую часть, и если пользователь не авторизован, никакого status-аттрибута у него естественно не будет. Крякнет.

**Comment by igorKichkar** [comment]
я где-то читал, что and работает до первого false, а or до первого true

**Comment by igorKichkar** [comment]
ты прав

**Comment by SuperLalka** [comment]
Ты верно написал, но это работает для самого питона, джанго же пытается получить все переменные
