### ISSUE TITLE
ReservationForm и ReservationFormForManager

### ISSUE THREAD

**Issue by SuperLalka** [igorKichkar/Parking-lot-management#6]
Мне непонятно что мешает переопределить метод __init__ сразу в ReservationForm и уже там, в зависимости от переданного контекста инициировать это поле или нет. Сейчас этим не занимайся, просто на будущее. Плодить формы, отличающиеся одним полем просто плохая идея

**Comment by igorKichkar** [comment]
пробовал, из-за чего-то не работало, до конца не разобрался еще
